### ISSUE TITLE
how to download the datasets

### ISSUE THREAD

**Issue by TaoCesc** [ydwen/opensphere#1]
Sorry, I don't find the way to download the datasets.

**Comment by wy1iu** [comment]
We are currently working on a convenient way to share the data, and will add the download links later. In the meantime, you can always download the data directly from the corresponding websites.

**Comment by wy1iu** [comment]
Hi, we have released the data. You can simply run ``bash scripts/dataset_setup.sh``.

**Comment by TaoCesc** [comment]
Thanks. Thank you so much for your work, inspiring good work. I will close the question.

**Comment by zikuicai** [comment]
@wy1iu  Thanks for sharing the script for dataset setup!
I have a few questions regarding the lfw dataset:
- Which algorithm did you use to get the aligned and cropped faces?
- And is there a reason for saving all the images as .bmp files?
- Why is the total number of images smaller than the original lfw dataset's?
