### ISSUE TITLE
Understanding figure 2 in the simPLE paper

### ISSUE THREAD

**Issue by ElisonSherton** [ydwen/opensphere#31]
Hi guys!

![image](https://github.com/ydwen/opensphere/assets/45599762/101b13c1-2c56-43f5-af6b-50abe9a487fd)

Consider Figure (b).
Assuming S denotes a measure of similarity, the aim of **Triplet proxy free PSL** is clear. We want to make Sp > Sn i.e. similarity between any two elements belonging to same class must be more than the similarity between any two elements belonging to a different class.

However in Figure (d),
If we assume S to be a measure of similarity, then similarity between any two elements of same class (Sp) must be more than a universal threshold (t) and the similarity between any to elements belonging to different classes must be less than a universal threshold (t), isn't it? Only then, that would mean the learned embedding space is suitable enough for an open-set recognition problem. In the figure the exact opposite of this is depicted. Does that mean S in figure 4 refers to distance or something?

Or I am misunderstanding something? Can someone please help clarify this figure for me?

Thanks,
Vinayak.

**Comment by ElisonSherton** [comment]
Hi @ydwen , @wy1iu 

Could you please help with this?

Thanks & Regards,
Vinayak.

**Comment by ydwen** [comment]
Hi ElisonSherton,

In this figure, we would like to demote similarity by S. So your understanding is correct: figure (d) shows the opposite, which is a typo. We will fix that in an updated version.

**Comment by ElisonSherton** [comment]
Thanks for the clarification.
